name: Hello

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/setup-node@v2.0.0

    - name: Setup Node.js
      uses: actions/setup-node@v2.0.0

    - name: Install Dependencies
      run: npm install

    - name: Run index.js to that logs hello world
      run: node index.js