name: you_just_worked_the_other_minute

on:
  push:
    branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.15.1

    - name: Install Dependencies
      run: npm install

    - name: Run Node.js script
      run: node index.js